stages:
  Prepare:
    cmd: "python -c \"from src.prepare import Prepare; Prepare.load(name='Prepare').run_and_save()\"\
      \ "
    deps:
    - data/data.xml
    - src/prepare.py
    params:
    - Prepare
    outs:
    - data/prepared/test.tsv
    - data/prepared/train.tsv
  Featurize:
    cmd: "python -c \"from src.featurization import Featurize; Featurize.load(name='Featurize').run_and_save()\"\
      \ "
    deps:
    - data/prepared/test.tsv
    - data/prepared/train.tsv
    - src/featurization.py
    params:
    - Featurize
    outs:
    - data/features/test.pkl
    - data/features/train.pkl
  Train:
    cmd: "python -c \"from src.train import Train; Train.load(name='Train').run_and_save()\"\
      \ "
    deps:
    - data/features/test.pkl
    - data/features/train.pkl
    - src/train.py
    params:
    - Train
    outs:
    - model.pkl
  Evaluate:
    cmd: "python -c \"from src.evaluate import Evaluate; Evaluate.load(name='Evaluate').run_and_save()\"\
      \ "
    deps:
    - model.pkl
    - src/evaluate.py
    metrics:
    - nodes/Evaluate/metrics_no_cache.json:
        cache: false
    plots:
    - prc.json:
        cache: false
    - roc.json:
        cache: false
