stages:
  prepare:
    cmd: 'python -c "from src.prepare import prepare; prepare(exec_func=True)" '
    deps:
    - data/data.xml
    - src/prepare.py
    params:
    - prepare
    outs:
    - data/prepared
  featurize:
    cmd: 'python -c "from src.featurization import featurize; featurize(exec_func=True)" '
    deps:
    - data/prepared
    - src/featurization.py
    params:
    - featurize
    outs:
    - data/features
  train:
    cmd: 'python -c "from src.train import train; train(exec_func=True)" '
    deps:
    - data/features
    - src/train.py
    params:
    - train
    outs:
    - model.pkl
  evaluate:
    cmd: 'python -c "from src.evaluate import evaluate; evaluate(exec_func=True)" '
    deps:
    - data/features
    - model.pkl
    - src/evaluate.py
    metrics:
    - scores.json:
        cache: false
    plots:
    - prc.json:
        cache: false
    - roc.json:
        cache: false
