Featurize:
    max_features: 500
    ngrams: 1
Prepare:
    seed: 20170428
    split: 0.2
Train:
    min_split: 2
    n_est: 50
    seed: 20170428
evaluate:
    min_split: 2
    n_est: 50
    seed: 20170428
featurize:
    max_features: 500
    ngrams: 1
prepare:
    seed: 20170428
    split: 0.2
train:
    min_split: 2
    n_est: 50
    seed: 20170428
